# Site settings
title: EMU UCiP
email: emuucip@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about the annual Eastern Michigan University Undergraduate Conference in Philosophy. Find advice for speakers and commentators, maps of campus, local hotels and restaurants, and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.emuucip.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  

# Build settings
# Build settings
kramdown:
  input: GFM
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
